-- Create table Titles
DROP TABLE IF EXISTS TITLES CASCADE;
CREATE TABLE TITLES (
    TITLE_ID VARCHAR(5) NOT NULL,
    TITLE VARCHAR(100) NOT NULL,
	PRIMARY KEY(TITLE_ID)
);

-- Create table Employees
DROP TABLE IF EXISTS EMPLOYEES CASCADE;
CREATE TABLE EMPLOYEES (
    EMP_NO INT NOT NULL,
    EMP_TITLE_ID VARCHAR(5) NOT NULL,
    BIRTH_DATE VARCHAR(50) NOT NULL,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    SEX VARCHAR(1) NOT NULL,
    HIRE_DATE VARCHAR(50) NOT NULL,
	FOREIGN KEY (EMP_TITLE_ID) REFERENCES TITLES(TITLE_ID),
	PRIMARY KEY(EMP_NO)
);

-- AS I COULD NOT IMPORT DATA FROM EMPLOYEES.CSV DUE TO A CONFLICT WITH THE DATA TYPE, I CREATED THE TABLE FIRST WITH VARCHARS, THEN IMPORT THE CSV FILE 
-- AND FINALLY CHANGE
ALTER TABLE EMPLOYEES ALTER COLUMN BIRTH_DATE TYPE DATE 
USING to_date(BIRTH_DATE, 'MM-DD-YYYY');

ALTER TABLE EMPLOYEES ALTER COLUMN HIRE_DATE TYPE DATE 
USING to_date(HIRE_DATE, 'MM-DD-YYYY');

-- Create table Departments
DROP TABLE IF EXISTS DEPARTMENTS CASCADE;
CREATE TABLE DEPARTMENTS (
    DEPT_NO VARCHAR(10) NOT NULL,
    DEPT_NAME VARCHAR(100) NOT NULL,
	PRIMARY KEY(DEPT_NO)
);

-- Create table Department Manager
DROP TABLE IF EXISTS DEPT_MANAGER CASCADE;
CREATE TABLE DEPT_MANAGER (
    DEPT_NO VARCHAR(10) NOT NULL,
    EMP_NO INT NOT NULL,
	FOREIGN KEY (EMP_NO) REFERENCES EMPLOYEES(EMP_NO),
	FOREIGN KEY (DEPT_NO) REFERENCES DEPARTMENTS(DEPT_NO),
	PRIMARY KEY(EMP_NO, DEPT_NO)
);

-- Create table Department Employee
DROP TABLE IF EXISTS DEPT_EMP CASCADE;
CREATE TABLE DEPT_EMP (
    EMP_NO INT NOT NULL,
	DEPT_NO VARCHAR(10) NOT NULL,
	FOREIGN KEY (EMP_NO) REFERENCES EMPLOYEES(EMP_NO),
	FOREIGN KEY (DEPT_NO) REFERENCES DEPARTMENTS(DEPT_NO),
	PRIMARY KEY(EMP_NO, DEPT_NO)
);

-- Create table Salaries
DROP TABLE IF EXISTS SALARIES CASCADE;
CREATE TABLE SALARIES (
    EMP_NO INT NOT NULL,
    SALARY INT NOT NULL,
	FOREIGN KEY (EMP_NO) REFERENCES EMPLOYEES(EMP_NO),
	PRIMARY KEY(EMP_NO)
);



